// <auto-generated />
using System;
using BE_U2_W1_D5.Models.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE_U2_W1_D5.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251205214741_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE_U2_W1_D5.Models.Entity.Anagrafica", b =>
                {
                    b.Property<int>("IDAnagrafica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDAnagrafica"));

                    b.Property<string>("CAP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDAnagrafica");

                    b.ToTable("Anagrafica");
                });

            modelBuilder.Entity("BE_U2_W1_D5.Models.Entity.TipoViolazione", b =>
                {
                    b.Property<int>("IDViolazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDViolazione"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDViolazione");

                    b.ToTable("TipoViolazione");
                });

            modelBuilder.Entity("BE_U2_W1_D5.Models.Entity.Verbale", b =>
                {
                    b.Property<int>("IDVerbale")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataTrascrizioneVerbale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataViolazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecurtamentoPunti")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndirizzoViolazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NominativoAgente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDVerbale");

                    b.ToTable("Verbale");
                });

            modelBuilder.Entity("BE_U2_W1_D5.Models.Entity.Verbale_Violazione", b =>
                {
                    b.Property<int>("IDVerbale")
                        .HasColumnType("int");

                    b.Property<int>("IDViolazione")
                        .HasColumnType("int");

                    b.HasKey("IDVerbale", "IDViolazione");

                    b.HasIndex("IDViolazione");

                    b.ToTable("Verbale_Violazione");
                });

            modelBuilder.Entity("BE_U2_W1_D5.Models.Entity.Verbale", b =>
                {
                    b.HasOne("BE_U2_W1_D5.Models.Entity.Anagrafica", "anagrafica")
                        .WithMany("Verbali")
                        .HasForeignKey("IDVerbale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("anagrafica");
                });

            modelBuilder.Entity("BE_U2_W1_D5.Models.Entity.Verbale_Violazione", b =>
                {
                    b.HasOne("BE_U2_W1_D5.Models.Entity.Verbale", "verbale")
                        .WithMany()
                        .HasForeignKey("IDVerbale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_U2_W1_D5.Models.Entity.TipoViolazione", "violazione")
                        .WithMany()
                        .HasForeignKey("IDViolazione")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("verbale");

                    b.Navigation("violazione");
                });

            modelBuilder.Entity("BE_U2_W1_D5.Models.Entity.Anagrafica", b =>
                {
                    b.Navigation("Verbali");
                });
#pragma warning restore 612, 618
        }
    }
}
